export const imagesMappingHe: { [key: string]: string } = {
  'א': 'bunny',
  'ב': 'swan',
  'ג': 'camel',
  'ד': 'bear',
  'ה': 'hippopotamus',
  'ו': 'rose',
  'ז': 'fly',
  'ח': 'cat',
  'ט': 'peacock',
  'י': 'owl',
  'כ': 'dog',
  'ל': 'lamur',
  'מ': 'jelly-fish',
  'נ': 'lepered',
  'ס': 'horse',
  'ע': 'bat',
  'פ': 'butterfly',
  'צ': 'turtle',
  'ק': 'rhinoceros',
  'ר': 'racoon',
  'ש': 'chimpanzee',
  'ת': 'alligator'
}

export const imagesMappingEn: { [key: string]: string } = {
  'a': 'antelope',
  'b': 'bear',
  'c': 'cat',
  'd': 'dog',
  'e': 'elephant',
  'f': 'frog',
  'g': 'goat',
  'h': 'horse',
  'i': 'iguana',
  'j': 'jellyfish',
  'k': 'kangaroo',
  'l': 'lion',
  'm': 'monkey',
  'n': 'narwhal',
  'o': 'owl',
  'p': 'penguin',
  'q': 'quail',
  'r': 'rabbit',
  's': 'sheep',
  't': 'tiger',
  'u': 'unicorn',
  'v': 'vulture',
  'w': 'wolf',
  'x': 'xylophone',
  'y': 'yak',
  'z': 'zebra'
}
